package io.github.mobilebytelabs.worker.web

/**
 * Returns the recommended Service Worker script that enables Background Sync for worker-kmp.
 *
 * Copy the returned content to the file served at [WebWorkManagerConfig.serviceWorkerScript]
 * (default `/worker-kmp-sw.js`), or serve it dynamically:
 *
 * ```js
 * // server.js (e.g. Node.js / Express)
 * app.get('/worker-kmp-sw.js', (req, res) => {
 *     res.type('application/javascript').send(backgroundSyncServiceWorkerScript());
 * });
 * ```
 *
 * The script handles two Service Worker events:
 * - **`sync`**: relays `{ type: "WORKER_KMP_SYNC", tag }` to all open window clients.
 * - **`message`**: forwards `WORKER_KMP_PING` back so the page can confirm SW registration.
 */
fun backgroundSyncServiceWorkerScript(): String = """
// worker-kmp Service Worker — Background Sync support
// Generated by worker-kmp. Copy to ${"/worker-kmp-sw.js"} or serve dynamically.

self.addEventListener('sync', function (event) {
    if (event.tag && event.tag.startsWith('worker-kmp-')) {
        event.waitUntil(
            self.clients
                .matchAll({ type: 'window', includeUncontrolled: true })
                .then(function (clients) {
                    clients.forEach(function (client) {
                        client.postMessage({ type: 'WORKER_KMP_SYNC', tag: event.tag });
                    });
                })
        );
    }
});

self.addEventListener('message', function (event) {
    if (event.data && event.data.type === 'WORKER_KMP_PING') {
        event.source.postMessage({ type: 'WORKER_KMP_PONG' });
    }
});
""".trimIndent()
