/*
 * Compose Multiplatform sample for worker-kmp + Store5.
 *
 * Demonstrates a minimal end-to-end CMP consumer of worker-kmp. After applying
 * the worker-app plugin + annotating commonMain (@WorkerKmpApp + @WorkerKmpAppContent),
 * the source tree contains ZERO per-platform Kotlin — launchers are codegened
 * into build/generated/.
 *
 * For projects that use build-logic + convention plugins, see
 * docs/getting-started/convention-plugin.md for a copy-pasteable Kotlin convention
 * plugin that wraps the wiring below.
 */

import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose)
    id("io.github.mobilebytelabs.worker-app")
}

group = "io.github.mobilebytelabs"
version = providers.gradleProperty("worker.version").get()

@OptIn(ExperimentalKotlinGradlePluginApi::class)
kotlin {
    jvm {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_11) }
        mainRun {
            // Generated by io.github.mobilebytelabs.worker-app from the
            // @WorkerKmpApp + @WorkerKmpAppContent functions in commonMain.
            mainClass.set("io.github.mobilebytelabs.worker.sample.composestore.di.generated.Generated_MainKt")
        }
    }

    listOf(iosArm64(), iosSimulatorArm64()).forEach { target ->
        target.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName.set("cmp-worker-sample-compose-store")
        browser {
            commonWebpackConfig { outputFileName = "cmp-worker-sample-compose-store.js" }
        }
        binaries.executable()
    }

    compilerOptions {
        optIn.add("kotlin.uuid.ExperimentalUuidApi")
        optIn.add("io.github.mobilebytelabs.worker.ExperimentalWorkerApi")
    }

    sourceSets {
        commonMain {
            dependencies {
                // worker-kmp all-in-one bundle (core + UI + Koin + Store5 + 4 platform actuals).
                implementation(project(":cmp-worker-compose-all"))
                implementation(libs.koin.compose)
                implementation(libs.kotlinx.coroutines.core)
                implementation(compose.runtime)
                implementation(compose.material3)
                implementation(compose.foundation)
                implementation(compose.ui)
            }
        }
        jvmMain {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(compose.preview)
            }
        }
    }
}
