/*
 * Compose Multiplatform sample for worker-kmp + Store5.
 *
 * Demonstrates how a real CMP consumer integrates worker-kmp:
 *  - Consumer brings their own KMP target matrix + Compose stack
 *  - Library wiring (worker-app plugin + cmp-worker-compose-all + koin-compose +
 *    worker opt-in) is encapsulated in a build-logic convention plugin
 *    (io.github.mobilebytelabs.worker.compose-sample) so an external project
 *    can lift the convention plugin into their own build-logic verbatim.
 *
 * After this setup the consumer source tree contains ZERO per-platform Kotlin —
 * launchers are codegened by the worker-app plugin into build/generated/.
 */

import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose)
    // Encapsulates worker-kmp library wiring (worker-app plugin + cmp-worker-compose-all
    // + koin-compose + ExperimentalWorkerApi opt-in). Source: build-logic/convention/
    // WorkerComposeConventionPlugin.kt — copy verbatim into any external project's
    // build-logic to get the same library setup.
    id("io.github.mobilebytelabs.worker.compose-sample")
}

group = "io.github.mobilebytelabs"
version = providers.gradleProperty("worker.version").get()

@OptIn(ExperimentalKotlinGradlePluginApi::class)
kotlin {
    jvm {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_11) }
        mainRun {
            // Generated by io.github.mobilebytelabs.worker-app from the
            // @WorkerKmpApp + @WorkerKmpAppContent functions in commonMain.
            mainClass.set("io.github.mobilebytelabs.worker.sample.composestore.di.generated.Generated_MainKt")
        }
    }

    listOf(iosArm64(), iosSimulatorArm64()).forEach { target ->
        target.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName.set("cmp-worker-sample-compose-store")
        browser {
            commonWebpackConfig { outputFileName = "cmp-worker-sample-compose-store.js" }
        }
        binaries.executable()
    }

    compilerOptions {
        optIn.add("kotlin.uuid.ExperimentalUuidApi")
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation(libs.kotlinx.coroutines.core)
                implementation(compose.runtime)
                implementation(compose.material3)
                implementation(compose.foundation)
                implementation(compose.ui)
            }
        }
        jvmMain {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(compose.preview)
            }
        }
    }
}
